name: Automatic Label Sync

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    label_sync:
        name: Automatic Label Synchronization
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
              with:
                  repository: "PixelPizza/.github"
            - name: Run Label Sync
              uses: crazy-max/ghaction-github-labeler@f4f6b96e7e747b5416cd470f3cfecf26abaa811e # v4
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  yaml-file: .github/labels.yml
